name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.83
          override: true
          components: clippy, rustfmt
      - name: Install Tree sitter CLI
        run: cargo install tree-sitter-cli
      - name: Install dependencies
        run: npm install
      - name: Tree sitter generate parser and run grammar tests
        run: tree-sitter g && tree-sitter t -u
